export const REDUCER_TYPES = {
    SET_PLAYER_NUM_CHANGE: "SET_PLAYER_NUM_CHANGE",
    START_SNAKE_LADDER: "START_SNAKE_LADDER",
    DICE_ROLLED: "DICE_ROLLED",
    TIME_OUT: "TIME_OUT",
    RESET_SNAKE_LADDER: "RESET_SNAKE_LADDER"
} 

export const SNAKES: any = {
    14: 3
}

export const LADDER: any  = {
    7: 12
}